version: 2.1

jobs:
  check:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Check
          command: |
            command -v docker-compose
            docker-compose --version

workflows:
  main:
    jobs:
      - check
